apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ccno-demo
    newName: localhost:5001/ccno-demo
    newTag: initial

replicas:
  - name: ccno-demo
    count: 2
